# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
before:
  hooks:
  - ./.git/hooks/pre-commit
  - nix flake check -L
binary_signs:
- ids:
  - cocopilot
builds:
- id: cocopilot
  main: ./cmd/cocopilot
  binary: bin/cocopilot
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -buildid=
  - -X main.version={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: amd64
  - goos: windows
    goarch: arm64
changelog:
  disable: true
checksum:
  name_template: 'checksums.txt'
gomod:
  proxy: true
  mod: readonly
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
nfpms:
- id: cocopilot
  ids:
  - cocopilot
  formats:
  - apk
  - archlinux
  - deb
  - rpm
  vendor: William Artero
  homepage: https://github.com/wwmoraes/cocopilot
  maintainer: William Artero <contact@artero.dev>
  description: cocopilot fetches API tokens to use GitHub Copilot with any tool
project_name: cocopilot
release:
  github:
    owner: wwmoraes
    name: cocopilot
  prerelease: auto
signs:
- artifacts: all
  ids:
  - cocopilot
snapshot:
  version_template: "{{- .RawVersion -}}+{{ .FullCommit }}"
