#:schema https://raw.githubusercontent.com/cocogitto/cocogitto/refs/heads/main/website/public/cog-schema.json

branch_whitelist = ["main"]
from_latest_tag = true
post_bump_hooks = [
  "git push",
  "git push origin {{version}}",
  "goreleaser release --clean --release-notes CHANGELOG.md",
]
pre_bump_hooks = [
  "nix-update --version {{version}} --flake cocopilot",
  "goreleaser check",
  "goreleaser healthcheck",
  "make check",
  "nix fmt",
]
tag_prefix = "v"

[git_hooks.commit-msg]
script = """#!/usr/bin/env sh
grep -q "^fixup! " "$1" || cog verify --file "$1"
git interpret-trailers --in-place --trailer signer --trailer patch-stack --trim-empty "$1"
"""

[git_hooks.post-checkout]
script = "make configure generate"

[git_hooks.pre-commit]
script = "make check"

[git_hooks.pre-push]
script = "om ci run --no-link && make dist"

[changelog]
authors = [{ signature = "William Artero", username = "wwmoraes" }]
owner = "wwmoraes"
package_template = "package_remote"
path = "CHANGELOG.md"
remote = "github.com"
repository = "cocopilot"
template = "remote"
